### ISSUE TITLE
Fix Broken Links on the Site

### ISSUE THREAD

**Issue by jalcine** [activitystreams/website#11] opened 2019-12-11 18:11 UTC
Someone mentioned that there's a lot of [broken links on Twitter][1].

[^1]: https://twitter.com/pete_tnt/status/1204824898457223169

**Comment by petetnt** [comment] 2019-12-11 18:14
This part:

> The Activity Streams format has already been adopted by BBC, Gnip, Google Buzz Gowalla, IBM, MySpace, Opera, Socialcast, Superfeedr, TypePad, Windows Live, YIID, and many others.

Most of those either 404, redirect to the the main site and/or in general don't exist anymore. Some fresher examples would be nice!

**Comment by petetnt** [comment] 2019-12-11 18:15
Dupe of #2 and #9 😸

**Comment by willnorris** [comment] 2019-12-11 19:02
fixed in 47d13cb

**Closed as completed by willnorris** 2019-12-11 19:02 UTC
